name: Pipeline

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build executado"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test executado"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy executado"